  //included header files and libraries
#include <iostream>
#include <string>
#include <iomanip>
#include <cstdlib>

  //include user defined header files and libraries
#include "FinalProjectDisclaimerMessage.h"
#include "Password.h"
#include "LoginMenu.h"
#include "UserNameMenu.h"
#include "UserName.h"

using namespace std;

int main()
{// --> MAIN START
 // --> CALL TO CONSTRUCTOR FOR FILE MESSAGE DISCLAIMER
  FinalProjectDisclaimerMessage DisclaimerMessage;
  // --> PRESS ENTER TO CONTINUE PROMPT
  cout << "ENTER ANY KEY TO CONTINUE." << endl;
  // --> ENTER ANY VALUE AND PRESS ENTER OR JUST PRESS ENTER
  getchar();
  // --> CLEAR SCREEN
  system("cls");
  // --> DISPLAY THE OPENING MESSAGE FOR THE BEGINING OF THE PROGRAM
  cout << "Welcome to Final Project Version 2." << endl;
  // --> CLEAR SCREEN
  system("cls");
  // --> CALL TO THE LOGIN MENU CONSTRUCTOR FILES
  LoginMenu Login1;
  return 0;
}//main end

/*
 	NEXT STEPS ARE TO WORK ON THE PASSWORD CREATOR AND THE USERNAME LOGIN SCREEN 
 PLACING THE MENU UP FOR THE GAMES TO BE PLAYED
 MAKING THE MONNEY TRANSACTION STAGES FOR THE RACECAR PORTION
 PLACING SOME SAVE FILES IN 
 USE OF POINTERS AND OVERLOADED FUNCTIONS
 PLACING A MAP IN THE GAME FOR TRAVEL POINTS AND LOCATIONS
 OPTIONAL HAVING A DAY OF THE WEEK GENERATOR
 GIVING THE USER A FEW ATTEMPTS AT LOGIN BEFORE PROGRAM SAYS THAT THE USER USED TO MANY ATTEMPTS
 PLACING A TRY/ CATCH IN FOR CERTAIN THINGS
 HAVING AN EXIT PROGRAM FUNCTION IN EVERY STAGE OF THE PROGRAM
 HAVING A WRITE AND SAVE FUNCTION IN THE PROGRAM FOR THE USER TO SEE THIER PROGRESS IN A TEXT FILE OR SOME OTHER FORM OF FILE
 PLACING A SET OR RULES IN THE PROGRAM
 PLACING A LIST OF COMMANDS FOR THE USER TO SEE DURING THE USE OF THE PROGRAM
 OPTIONAL HAVING A HIDDEN FEATURE IN THE PROGRAM
 HAVING SEVERAL MORE HEADER AND CPP FILES HANDY FOR DIFFERENT THINGS WITHINI THE PROGRAM
 ALLOWING THE USER TO CHANGE THIER NAME A MAX NUMBER OF TIMES
 GIVE THE USE A LIMIT OF THINGS THEY CAN ACCOMPLISH WITHIN THE DAY BEFORE THE PROGRAM SAYS THE DAY IS OVER
 PLACE A TIMER IN THE PROGRAM THAT TRACKS THE AMOUNT OF TIME SPENT ON A TASK.
 */
